package Observer;

public interface OffertaObserver {
    //RAPPRESENTA GLI OSSERVATORI (CONTRATTO CHE GLI OSSERVATORI DEVONO SEGUIRE)
    // CIOE' QUALI METODI DEVONO ESEGUIRE PER ESSERE PER RICEVERE LE NOTIFICHE DAL SOGGETTO(UTENTI MODEL)

}

